### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Torinde** [crazii/USBDDOS#4]
The "Modified BSD License", a.k.a. the "3-Clause BSD License", is compatible with GPLv2.

See https://www.gnu.org/licenses/license-list.en.html#ModifiedBSD

So no problem, and nothing unclear about it.

But I am puzzled why the USBDDOS source code is apparently licensed under the GNU Affero General Public License, as opposed to the regular (non-Affero) GPL, since I can't think of any realistic scenario where the USBDDOS would be used to host a website or web service.

But regular GPL apparently includes a clause that says it may be combined with Affero GPL software (as long as it's the same version number, I assume?)

Speaking of GPL versions: GPLv3 is a can of worms and not necessarily compatible with all GPLv2 code (it depends on whether or not the GPLv2 license on the code includes the optional "or later" clause).

Yeah, software licenses are confusing, I know. 🫠

By the way, does this seemingly forgotten project on Google Code actually already support EHCI?

_Originally posted by @volkertb in https://github.com/crazii/USBDDOS/issues/2#issuecomment-1865161435_

@crazii, what do you think about defining a license for USBDDOS, considering the above about the Google Code page?

**Comment by crazii** [comment]
Yes thanks for your screenshot of information. I will add a license file quite soon.
